development:
  adapter: postgresql
  encoding: utf8
  database: rating_dev
  pool: 5
  username:
  password:
  host: localhost

test:
  adapter: postgresql
  encoding: utf8
  database: rating_test
  pool: 5
  username:
  password:

production:
  adapter: postgresql
  encoding: utf8
  database: rating_production
  pool: 5
  username:
  password: